[tool.poetry]
name = "uncluttr"
version = "0.1.0"
description = ""
authors = ["Waldeck <Waldeck.ernst.felix@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
watchdog = "^6.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
